apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
  - name: etcd-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: etcd-4001
    port: 4001
    protocol: TCP
    targetPort: 4001
  - name: etcd-7001
    port: 7001
    protocol: TCP
    targetPort: 7001    
  selector:
    app: etcd

---
kind: Service
apiVersion: v1
metadata:
   name: etcd-0
   labels:
     etcd_node: etcd-0
spec:
  selector:
    etcd_node: etcd-0
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: server
      port: 2380
      protocol: TCP
      targetPort: 2380
    - name: etcd-4001
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: etcd-7001
      port: 7001
      protocol: TCP
      targetPort: 7001    

---
kind: Pod
apiVersion: v1
metadata:
  name: etcd-0
  labels:
    app: etcd
    etcd_node: etcd-0
spec:
      containers:
        - name: etcd-0
          image: quay.io/coreos/etcd:latest
          command:
            - /usr/local/bin/etcd
            - --name
            - etcd-0
            - --initial-advertise-peer-urls
            - http://etcd-0:2380
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://etcd-0:2379
            - --initial-cluster
            - etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
            - --initial-cluster-state
            - new
          ports:
            - name: legacy-port-1 
              containerPort: 4001
              hostPort: 4001
              protocol: TCP
            - name: legacy-port-2
              containerPort: 7001
              hostPort: 7001
              protocol: TCP
            - name: client
              containerPort: 2379
              hostPort: 2379
              protocol: TCP
            - name: server
              containerPort: 2380
              hostPort: 2380
              protocol: TCP
      nodeSelector:
        name: node1

---

kind: Service
apiVersion: v1
metadata:
   name: etcd-1
   labels:
     etcd_node: etcd-1
spec:
  selector:
    etcd_node: etcd-1
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: server
      port: 2380
      protocol: TCP
      targetPort: 2380
    - name: etcd-4001
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: etcd-7001
      port: 7001
      protocol: TCP
      targetPort: 7001

---
kind: Pod
apiVersion: v1
metadata:
  name: etcd-1
  labels:
    app: etcd
    etcd_node: etcd-1
spec:
      containers:
        - name: etcd-1
          image: quay.io/coreos/etcd:latest
          command:
            - /usr/local/bin/etcd
            - --name
            - etcd-1
            - --initial-advertise-peer-urls
            - http://etcd-1:2380
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://etcd-1:2379
            - --initial-cluster
            - etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
            - --initial-cluster-state
            - new
          ports:
            - name: legacy-port-1
              containerPort: 4001
              hostPort: 4001
              protocol: TCP
            - name: legacy-port-2
              containerPort: 7001
              hostPort: 7001
              protocol: TCP
            - name: client
              containerPort: 2379
              hostPort: 2379
              protocol: TCP
            - name: server
              containerPort: 2380
              hostPort: 2380
              protocol: TCP
      nodeSelector:
        name: node2

---
kind: Service
apiVersion: v1
metadata:
   name: etcd-2
   labels:
     etcd_node: etcd-2
spec:
  selector:
    etcd_node: etcd-2
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: server
      port: 2380
      protocol: TCP
      targetPort: 2380
    - name: etcd-4001
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: etcd-7001
      port: 7001
      protocol: TCP
      targetPort: 7001


---
kind: Pod
apiVersion: v1
metadata:
  name: etcd-2
  labels:
    app: etcd
    etcd_node: etcd-2
spec:
      containers:
        - name: etcd-2
          image: quay.io/coreos/etcd:latest
          command:
            - /usr/local/bin/etcd
            - --name
            - etcd-2
            - --initial-advertise-peer-urls
            - http://etcd-2:2380
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://etcd-2:2379
            - --initial-cluster
            - etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
            - --initial-cluster-state
            - new
          ports:
            - name: legacy-port-1
              containerPort: 4001
              hostPort: 4001
              protocol: TCP
            - name: legacy-port-2
              containerPort: 7001
              hostPort: 7001
              protocol: TCP
            - name: client
              containerPort: 2379
              hostPort: 2379
              protocol: TCP
            - name: server
              containerPort: 2380
              hostPort: 2380
              protocol: TCP
      nodeSelector:
        name: node3


